create schema if not exists data_lifecycles_mvp;

create table if not exists data_lifecycles_mvp.import_run (
    import_run_id bigint generated by default as identity primary key,
    source_name text not null,
    source_file text,
    import_status text not null default 'pending',
    notes text,
    imported_at timestamptz not null default now()
);

create table if not exists data_lifecycles_mvp.catalogue_record_raw (
    raw_record_id bigint generated by default as identity primary key,
    import_run_id bigint references data_lifecycles_mvp.import_run(import_run_id) on delete set null,
    source_name text not null,
    supplier text,
    raw_name text not null,
    payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists data_lifecycles_mvp.asset (
    asset_id bigint generated by default as identity primary key,
    data_id text not null unique,
    common_name text not null,
    data_class text,
    product_family text,
    iso_category text,
    supplier text,
    open_proprietary text,
    coverage text,
    origin_company text,
    source text,
    match_status text,
    populated_by text,
    confidence numeric(5,2),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists data_lifecycles_mvp.asset_variant (
    variant_id bigint generated by default as identity primary key,
    asset_id bigint references data_lifecycles_mvp.asset(asset_id) on delete cascade,
    raw_name text not null,
    normalized_name text,
    common_name text,
    supplier text,
    product_family text,
    iso_category text,
    coverage text,
    open_proprietary text,
    origin_company text,
    import_run_id bigint references data_lifecycles_mvp.import_run(import_run_id) on delete set null,
    created_at timestamptz not null default now()
);

create table if not exists data_lifecycles_mvp.asset_reconciliation (
    reconciliation_id bigint generated by default as identity primary key,
    asset_id bigint references data_lifecycles_mvp.asset(asset_id) on delete cascade,
    lifecycle_common_name text not null,
    catalogue_matches text,
    match_type text not null,
    confidence numeric(5,2),
    populated_by text,
    review_status text not null default 'needs_review',
    reviewed_by uuid,
    reviewed_at timestamptz,
    notes text,
    created_at timestamptz not null default now()
);

create table if not exists data_lifecycles_mvp.project_type (
    project_type_id bigint generated by default as identity primary key,
    name text not null unique,
    sector_group text
);

create table if not exists data_lifecycles_mvp.project_stage (
    stage_id bigint generated by default as identity primary key,
    project_type_id bigint not null references data_lifecycles_mvp.project_type(project_type_id) on delete cascade,
    stage_name text not null,
    stage_sequence integer,
    unique (project_type_id, stage_name)
);

create table if not exists data_lifecycles_mvp.stage_asset_requirement (
    requirement_id bigint generated by default as identity primary key,
    requirement_key text unique,
    project_type_id bigint not null references data_lifecycles_mvp.project_type(project_type_id) on delete cascade,
    stage_id bigint not null references data_lifecycles_mvp.project_stage(stage_id) on delete cascade,
    asset_id bigint references data_lifecycles_mvp.asset(asset_id) on delete set null,
    data_id text,
    common_name text not null,
    stage_data_role text,
    role_code text,
    used_in_stage text,
    activity text,
    populated_by text,
    confidence numeric(5,2),
    notes text,
    lookup_key text
);

create table if not exists data_lifecycles_mvp.manual_addition (
    addition_id bigint generated by default as identity primary key,
    project_type_id bigint references data_lifecycles_mvp.project_type(project_type_id) on delete set null,
    data_id text,
    common_name text not null,
    data_class text,
    product_family text,
    iso_category text,
    supplier text,
    open_proprietary text,
    coverage text,
    origin_company text,
    catalogue_variant_names text,
    target_roles text,
    source text,
    created_at timestamptz not null default now()
);

create table if not exists data_lifecycles_mvp.client_usage_submission (
    submission_id bigint generated by default as identity primary key,
    requested_by uuid,
    client_name text,
    project_type text,
    stage_name text,
    common_name text not null,
    suggestion_type text not null,
    suggested_value text,
    evidence_note text,
    submission_status text not null default 'submitted',
    created_at timestamptz not null default now(),
    reviewed_at timestamptz,
    reviewed_by uuid
);

create table if not exists data_lifecycles_mvp.review_queue (
    review_queue_id bigint generated by default as identity primary key,
    queue_type text not null,
    reference_table text not null,
    reference_id bigint not null,
    priority text not null default 'medium',
    status text not null default 'open',
    confidence numeric(5,2),
    summary text not null,
    created_at timestamptz not null default now(),
    assigned_to uuid,
    resolved_at timestamptz
);

create table if not exists data_lifecycles_mvp.audit_log (
    audit_log_id bigint generated by default as identity primary key,
    actor_user_id uuid,
    actor_role text,
    action text not null,
    entity_name text not null,
    entity_id text not null,
    change_summary jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_asset_common_name on data_lifecycles_mvp.asset using gin (to_tsvector('simple', common_name));
create index if not exists idx_asset_match_status on data_lifecycles_mvp.asset (match_status);
create index if not exists idx_variant_raw_name on data_lifecycles_mvp.asset_variant using gin (to_tsvector('simple', raw_name));
create index if not exists idx_requirement_project_stage on data_lifecycles_mvp.stage_asset_requirement (project_type_id, stage_id);
create index if not exists idx_review_queue_status on data_lifecycles_mvp.review_queue (status, queue_type);
create index if not exists idx_submission_status on data_lifecycles_mvp.client_usage_submission (submission_status);
